name: Deploy scrapper to azure functions

on:
  [push]

env:
  AZURE_FUNCTION_APP_NAME: 'scrapper-func'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Python ${{env.PYTHON_VERSION}} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: 'Resolve project dependencies using pip'
        shell: bash
        run: |
          pushd '${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{env.AZURE_FUNCTION_APP_NAME}}
          package: ${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}
          publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
